# Site settings
title: Arthur Brasil
tag_text: Arthur Brasil
description: Sobre o canal do YouTube "Jogos do Arthur"

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
